### ISSUE TITLE
EC2 instance not responding on port 8080

### ISSUE THREAD

**Issue by G0d3r** [brikis98/terraform-up-and-running-code#101]
Hello everyone! I’m Ernest and I’m currently reading the book Terraform Up & Running 2nd version. 
I noted an issue when I wanted to use created EC2 instance on AWS and the public IPv4 address which does not work at all.
 
I am stuck with this problem for a couple of days now and I can’t find any information on the Internet.
I noted also that many readers have the same issue when I was searching for the answer.

I used the source code which is the book but unfortunately, it does not work. I decided to correct a little the source code which is in book and now it looks as below but still iPv4 it does not respond.
![screenshot-1](https://user-images.githubusercontent.com/47259706/225009365-3e96deb8-bbf8-4042-ac4f-c5c6701f7ad9.png)
<img width="407" alt="sceenshot-2" src="https://user-images.githubusercontent.com/47259706/225009399-a19d0f21-cbc7-45b7-8074-27ebedfded6c.png">

```
provider "aws" {
  region = "eu-central-1"
}

resource "aws_security_group" "instance" {
  name = "aws-terraform-example-instance"
 ingress {
    from_port        = 8080
    to_port          = 8080
    protocol         = "tcp"
    cidr_blocks      = ["0.0.0.0/0"]
  }
  
   ingress {
    from_port        = 80
    to_port          = 80
    protocol         = "tcp"
    cidr_blocks      = ["0.0.0.0/0"]
  }
  
   ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "ALL"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_instance" "example" {
  ami           = "ami-08f13e5792295e1b2"
  instance_type = "t2.micro"

  user_data = <<-EOF
                #!/bin/bash
                echo "Hello, World 2" > index.html
                nohup python3 -m http.server 8080 &
                EOF
  tags = {
    Name = "aws-terraform-example"
  }
}

output "public_ip" {
  value = "${aws_instance.example.public_ip}"
  description = "Public IP address"
}

```
Please help.

**Comment by brikis98** [comment]
It looks like you created a security group, but you didn't actually attach it to your EC2 instance! You need to set the `vpc_security_group_ids` parameter on the `aws_instance` resource:

```hcl
resource "aws_instance" "example" {
  ami           = "ami-08f13e5792295e1b2"
  instance_type = "t2.micro"

  user_data = <<-EOF
                #!/bin/bash
                echo "Hello, World 2" > index.html
                nohup python3 -m http.server 8080 &
                EOF
  tags = {
    Name = "aws-terraform-example"
  }

  # This attaches your security group to the EC2 instance
  vpc_security_group_ids = aws_security_group.instance.id
}
```

**Comment by G0d3r** [comment]
Thank you @brikis98 indeed, now it works! I missed that for some reason when I read this book.

**Comment by brikis98** [comment]
Great to hear! Thanks for following up.
