### ISSUE TITLE
Heredoc leading whitespace in user data

### ISSUE THREAD

**Issue by syl20bnr** [brikis98/terraform-up-and-running-code#12]
On my system (macOS Sierra) using terraform version 0.9.3 I need to completely remove any leading whitespace otherwise the user data is not executed.

The following format does not work:

```
resource "aws_instance" "example" {
  tags {
    Name = "terraform-example"
  }
  ami = "ami-f4cc1de2"
  instance_type = "t2.micro"
  vpc_security_group_ids = ["${aws_security_group.webserver.id}"]
  user_data = <<EOF
    #!/bin/bash
    echo "Hello, Terraform!" > index.html
    nohup busybox httpd -f -p 8080 &
    EOF
}
```

Whereas it works without the leading whitespace:

```
resource "aws_instance" "example" {
  tags {
    Name = "terraform-example"
  }
  ami = "ami-f4cc1de2"
  instance_type = "t2.micro"
  vpc_security_group_ids = ["${aws_security_group.webserver.id}"]
  user_data = <<EOF
#!/bin/bash
echo "Hello, Terraform!" > index.html
nohup busybox httpd -f -p 8080 &
EOF
}
```

**Comment by brikis98** [comment]
This is why all the examples in the book use `<<-EOF...EOF` and not `<<EOF...EOF`. The dash in `<<-EOF` means that leading whitespace should be trimmed. If you remove that dash, then yes, you'll have to manually remove the whitespace too.

**Comment by syl20bnr** [comment]
Closing this as it is closely related with #11
