### ISSUE TITLE
Examples don't work with TF < 9

### ISSUE THREAD

**Issue by neybar** [brikis98/terraform-up-and-running-code#13]
I've started with the exercises in chapter 2, but all of them are restricted to terraform < 9.  I'm not familiar enough yet with terraform to know if I can just rip that out, and if things should still work.

I also noticed that some of the AMI id's don't resolve.

**Comment by brikis98** [comment]
Most of the examples will work just fine with Terraform 0.9, so feel free to remove that check. I only had it there as I haven't had a chance to run all the tests against them yet. I hope to do so in the next couple weeks.

**Comment by bbright024** [comment]
just worked through ch2 today, Apr 24 2018

user_data = <<-EOF    doesn't work, needs to be   user_data = <<EOF

that's the only issue I had.  the ubuntu image still works.

**Comment by brikis98** [comment]
> user_data = <<-EOF doesn't work, needs to be user_data = <<EOF

`<<-EOF` works just fine for me with `terraform 0.11`. What issue are you seeing?

**Comment by bbright024** [comment]
I'm using 0.11.5 on Linux - 4.13.0-39-generic #44-Ubuntu 

Error: Error parsing /home/bbright/tf_up_and_running/main.tf: object expected closing RBRACE got: EOF

This error goes away when I delete the '-' before the first 'EOF'. 

From https://www.terraform.io/docs/configuration/syntax.html

> Multiline strings can use shell-style "here doc" syntax, with the string starting with a marker like <<EOF and then the string ending with EOF on a line of its own. The lines of the string and the end marker must not be indented.

**Comment by bbright024** [comment]
ah yeah, here ya go.  This code results in the error I got, and it goes away by deleting that '-' infront of the EOF. 

`resource "aws_launch_configuration" "example" {
  image_id = "ami-40d28157" # ubuntu                                                                                         
  instance_type = "t2.micro"

  security_groups = ["${aws_security_group.instance.id}"]

  user_data = <<-EOF                                                                                                         
#!/bin/bash                                                                                                                  
echo "Hello, World, tf here" > index.html                                                                                    
nohup busybox httpd -f -p "${var.server_port}" &                                                                             
EOF                                                                                                                          

  lifecycle {
    create_before_destroy = true
  }
}
`

**Comment by brikis98** [comment]
The key with the `<<-EOF` heredoc format is that its whitespace sensitive. It's designed to allow you to indent your source code, without the resulting string being indented. If you look at the chapter 2 code, it uses very careful indentation. If you copy that, you'll probably find that `<<-EOF` works for you too.

**Comment by bbright024** [comment]
Ah, ok.  The difference in format in the book vs my format and the terraform.io example format did strike me as strange.  

Thanks for your time!

**Comment by brikis98** [comment]
Closing issue from ~2 years ago. _[Terraform: Up & Running, 2nd edition](https://blog.gruntwork.io/terraform-up-running-2nd-edition-is-out-7de640c1576d) came out in 2019 and is compatible with TF 0.12 and above only.
