### ISSUE TITLE
[Errata] Chapter 3, Page 74, MySQL database cannot be destroyed

### ISSUE THREAD

**Issue by ju2wheels** [brikis98/terraform-up-and-running-code#15]
Using the resource definition in Chapter 3, page 74 to create a MySQL db works fine, but due to missing parameters (and possible existing bugs in Terraform that there are open issues for) you will not be able to destroy the MySQL instance:

```
resource "aws_db_instance" "example" {
  engine = "mysql"
  allocated_storage = 10
  instance_class = "db.t2.micro"
  name = "example_database"
  username = "admin"
  password = "${var.db_password}"
}
```

The reason this cant be destroyed is because this resource (per [documentation](https://www.terraform.io/docs/providers/aws/r/db_instance.html)) expects the `final_snapshot_identifier` and/or the `skip_final_snapshot` parameters to be defined, as the default is to take a snapshot on destroy. However since we havent defined the snapshot identifier it throws an error. Unfortunately, adding `skip_final-snapshot = true` after having created the resource doesnt work (which may or may not be a bug according to the existing issue https://github.com/hashicorp/terraform/issues/5417).

Therefore be sure to use the following for all examples:

```
resource "aws_db_instance" "example" {
  engine = "mysql"
  allocated_storage = 10
  instance_class = "db.t2.micro"
  name = "example_database"
  username = "admin"
  password = "${var.db_password}"
  skip_final_snapshot = true
}
```

**Comment by brikis98** [comment]
Thanks for reporting. I ran tests on all of the code that called both `apply` and `destroy` and never hit this issue. Nevertheless, I added the `skip_final_snapshot = true` setting to each resource just now, so hopefully people won't run into this issue in the future.
