### ISSUE TITLE
Chapter 4: db_remote_state_* hard-coded in book but variables in examples

### ISSUE THREAD

**Issue by mjuenema** [brikis98/terraform-up-and-running-code#16]
I noticed that in chapter 4 in the book the `db_remote_state_bucket` and `db_remote_state_key` arguments in the `module "webserver_cluster"` example are hard-coded (albeit with a place-holder *(YOUR_BUCKET_NAME)* value for  `db_remote_state_bucket`) but on Github those arguments are variables defined in `vars.tf`.

**Comment by brikis98** [comment]
Yes, there are minor changes from the book to the sample code, mostly so I could easily run the sample code through automated tests.

**Comment by brikis98** [comment]
Is this causing any problems for you?

**Comment by mjuenema** [comment]
No not at all.
