### ISSUE TITLE
 Error deleting S3 Bucket

### ISSUE THREAD

**Issue by payamzowghi** [brikis98/terraform-up-and-running-code#2]
at the end of chapter 3, after I ran terragrunt apply, I got this error:
* aws_s3_bucket.terraform_state: Error deleting S3 Bucket: BucketNotEmpty: The bucket you tried to delete is not empty. You must delete all versions in the bucket.

what does it mean?
my server cluster access' the database.and I can open the browser.but I got the error.

**Comment by brikis98** [comment]
Did you remove the `aws_s3_bucket` resource from your code? If so, then Terraform is going to try to delete your S3 bucket. However, AWS won't allow it to do that unless you empty the bucket first.

**Comment by payamzowghi** [comment]
I'm curious to know that why don't you use the module to create data store in chapter 4,like webserver-cluster?
because it is possible.

**Comment by brikis98** [comment]
> I'm curious to know that why don't you use the module to create data store in chapter 4,like webserver-cluster?

Not sure I understand your question. What module are you referring to?

**Comment by payamzowghi** [comment]
I mean the Terraform module.

**Comment by brikis98** [comment]
I'm still not following. Could you provide a bit more context? What Terraform module? Are you still asking about the S3 bucket stuff or is this a totally separate set of questions?

**Comment by payamzowghi** [comment]
In chapter 4, you create a reusable infrastructure with Terraform modules to generate staging(webserver-cluster) and production(webserver-cluster). we can use the way to generate staging(data-stores) and production(data-stores)?

**Comment by brikis98** [comment]
Yes. You could definitely put the DB code in its own module and use that same module in both `stage` and `prod`.

**Comment by brikis98** [comment]
Closing this issue, since I think the question about S3 has been answered.
