### ISSUE TITLE
terragrunt version

### ISSUE THREAD

**Issue by jhagege** [brikis98/terraform-up-and-running-code#21]
Hi, amazing book ! 
Which version of terragrunt has been used with this book ? Would like to be as close as possible to examples. 
Thanks :)

**Comment by brikis98** [comment]
Thanks!

I don't think any of the examples in this repo require or use Terragrunt. They should use just plain Terraform and work with any Terragrunt version.

**Comment by brikis98** [comment]
I believe the question here was answered. Closing.
