### ISSUE TITLE
why was terragrunt removed from this code?

### ISSUE THREAD

**Issue by ms4720** [brikis98/terraform-up-and-running-code#24]
The book has it in examples, why was it pulled from the example code?

**Comment by brikis98** [comment]
IIRC, the book has only a small, single Terragrunt example. The [Terragrunt docs](https://github.com/gruntwork-io/terragrunt) have far more. Is there something specific you're looking for?

**Comment by ms4720** [comment]
Just curious, I saw the notes for terragrunt being removed from the code and that is where I am in the book

**Comment by brikis98** [comment]
Ah, the commits removing Terragrunt were from before the book was published 😄 

I used to have more Terragrunt references in the book, but they didn't add much, and were just confusing, so I removed them.

**Comment by ms4720** [comment]
ok, thanks
