### ISSUE TITLE
Simple examples assume that account has default VPC

### ISSUE THREAD

**Issue by PSLLSP** [brikis98/terraform-up-and-running-code#26]
Simple examples silently assume that account (region) has default VPC. Simple examples use us-east-1, the oldest AWS region, so there is a chance that older account is "EC2-clasic" and doesn't have default VPC and related infrastructure.
That is difficult for beginner to fix these issues.

https://docs.aws.amazon.com/vpc/latest/userguide/default-vpc.html
 
That is my case, simple examples fail when I try them in region us-east-1. It is "difficult" to modify examples to use vpc-id, etc. The easiest workaround is to use different region, like us-east-2 (Ohio), that should have default VPC because it was added recently and default VPC is always there.

**Comment by brikis98** [comment]
Well, I'm not sure it's "silent" as the book has a clear warning early on that we use the Default VPC to try to keep the examples simple. 

That said, using a different region than us-east-1 does seem like a clever way to increase the odds that the VPC exists. I'll keep it in mind for the 2nd edition of the book, though a PR to make the change now is very welcome!

**Comment by brikis98** [comment]
This issue was fixed in _[Terraform: Up & Running, 2nd edition](https://blog.gruntwork.io/terraform-up-running-2nd-edition-is-out-7de640c1576d)_, which came out in 2019, and uses `us-east-2` as the default region. There are also clear warnings/instructions about what to do if you don't have a default VPC.
