### ISSUE TITLE
Chapter 2 Error Availability Zones in WebServer Cluster

### ISSUE THREAD

**Issue by JamesAndresCM** [brikis98/terraform-up-and-running-code#33]
- Message: 
**Inappropriate value for attribute "availability_zones": element 0: string
required.**

¿ How to fix ?
- Replace 
```availability_zones = ["${data.aws_availability_zones.all.names}"]```
- To
```availability_zones = ["${data.aws_availability_zones.all.names[0]}"]```

**Comment by brikis98** [comment]
Are you using code form the `master` branch? Are you on Terraform 0.12? Are you reading the 2nd edition of the book?

**Comment by brikis98** [comment]
No response for over a year, closing.

**Comment by danielk0121** [comment]
```
availability_zones = data.aws_availability_zones.all.names
```
it works for me

```
terraform {
  required_version = "0.12.23"
  required_providers {
    aws = ">= 2.53.0"
  }
}
```
