### ISSUE TITLE
page 36 Chef Diagram adjustment

### ISSUE THREAD

**Issue by clavery-chef** [brikis98/terraform-up-and-running-code#34]
Hi! 

Great work on getting a 2nd edition out and updated for 0.12. Just thought I'd flag up the the diagram on page 36 - The nomenclature isn't quite consistent with how chef would phrase this - see https://docs.chef.io/chef_overview.html. If you change out the chef users machine to chef workstation, the And the diagram the the target nodes could be labelled @App Server, each Running Chef-Client", that'd make more sense in reference to the published architecture. 

Feel free to talk about how application automation is different from CM or IAC provisioning tools - there's a habitat provisioner for terraform just for that. ;)

Thanks,
Chris

![Chef-infra_diagram](https://user-images.githubusercontent.com/47523605/62803896-9dd78300-bae3-11e9-8eab-102560fcd0a3.png)

**Comment by brikis98** [comment]
Thanks for the suggestions! Let me make sure I have the terminology right:

From left to right on the image, it should be:

- Chef workstation
- Chef server
- App servers, each running Chef client

Is that right?

**Comment by clavery-chef** [comment]
👍

**Comment by brikis98** [comment]
Got it, thanks!

**Comment by brikis98** [comment]
This issue was fixed in _[Terraform: Up & Running, 2nd edition](https://blog.gruntwork.io/terraform-up-running-2nd-edition-is-out-7de640c1576d)_, which came out in 2019.
