### ISSUE TITLE
page 161-162 slieve typo

### ISSUE THREAD

**Issue by clavery-chef** [brikis98/terraform-up-and-running-code#35]
"Now you've seen all the tricks the init command should have up its slieve!" should read "Now you've seen all the tricks the init command should have up its sleeve!"

slieve - an Irish mountain / sleeve  - the arm of a garment :)

**Comment by brikis98** [comment]
Hahaha, good catch, thanks! I'll make sure this gets fixed 👍

**Comment by brikis98** [comment]
Fixed now. Will be out in the next push of the early release and in the final version. Thx!
