### ISSUE TITLE
Error launching source instance: InvalidAMIID.NotFound: The image id '[ami-0c55b159cbfafe1f0]'

### ISSUE THREAD

**Issue by yatakoi** [brikis98/terraform-up-and-running-code#41]
Hello.

Using Deploy a Single Server as an example, I get an error.

`aws_instance.example: Creating...

Error: Error launching source instance: InvalidAMIID.NotFound: The image id '[ami-0c55b159cbfafe1f0]' does not exist
        status code: 400, request id: f5e8a0a2-0de9-4476-ad8b-c3473f93532c

  on main.tf line 5, in resource "aws_instance" "example":
   5: resource "aws_instance" "example" {`

**Comment by brikis98** [comment]
Did you change the AWS region in the `provider` block? If so, each AMI ID lives in only one region, so you'll have to replace the AMI ID with a different ID for your new region.

**Comment by shrutikamehta369** [comment]
That's right. I have changed the region. Its working now.

Thanks

**Comment by ale-fante** [comment]
Yup... the region!
