### ISSUE TITLE
chapter 2 user data

### ISSUE THREAD

**Issue by davidATsains** [brikis98/terraform-up-and-running-code#42]
I am learning Terraform using this book. I am chapter 2 section: Deploy a single web server.
i followed the code and everything.
but when I curl the public ip:8080,  
I have already tried curl http://elastic_instance_public_ip:8080 and 
curl https://elastic_instance_public_ip:8080

the result is Operation timed out
How do I solve this issue. 

Below is my code:
```
provider "aws" {
  version = "~>2.0"
  region  = "eu-west-1"

}

resource "aws_instance" "example" {
  ami                    = "ami-01f14919ba412de34"
  instance_type          = "t2.micro"
  vpc_security_group_ids = [aws_security_group.instance.id]

  user_data = <<-EOF
              #!/bin/bash
              echo "Hello Sainsburys" > index.html
              nohup busybox httpd -f -p 8080 &
              EOF

  tags = {
    Name = "test-example"
  }
}

resource "aws_security_group" "instance" {
  name = var.security_group_name

  ingress {
    from_port   = 8080
    to_port     = 8080
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

variable "security_group_name" {
  description = "The name of the security group"
  default     = "terraform-example-instance"
}
output "public_ip" {
  value = aws_instance.example.public_ip
  description = "The public IP of the instance"
}
```

**Comment by brikis98** [comment]
You're running `ami-01f14919ba412de34`, which I believe is Amazon Linux. This AMI does not have `busybox` installed by default, so the User Data script is likely failing. You can most likely verify this by [looking at the system log](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-console.html#instance-console-console-output) of your EC2 instance; it's a bit hard to dig it out, but it'll probably have an error about `busybox` not being found.

In the book, I use Ubuntu by default, so you may want to switch to that if you're going to use `busybox`.

**Comment by davidATsains** [comment]
> You're running `ami-01f14919ba412de34`, which I believe is Amazon Linux. This AMI does not have `busybox` installed by default, so the User Data script is likely failing. You can most likely verify this by [looking at the system log](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-console.html#instance-console-console-output) of your EC2 instance; it's a bit hard to dig it out, but it'll probably have an error about `busybox` not being found.
> 
> In the book, I use Ubuntu by default, so you may want to switch to that if you're going to use `busybox`.

thank you

**Comment by vim-diesel** [comment]
still fails on ubuntu

**Comment by yantaq** [comment]
I ran AMI and I solved the connection refused error by replaced the line:
   
    `nohup busybox httpd -f -p 8080 &`
with
 
       `nohup python -m SimpleHTTPServer 8080 &`

**Comment by amelvin** [comment]
As per the author comment, switching to an Ubuntu instance worked for me with no other changes:

Terraform v1.3.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.34.0
