### ISSUE TITLE
chapter 3 issue

### ISSUE THREAD

**Issue by davidATsains** [brikis98/terraform-up-and-running-code#45]
Hello, i am currently using this book to learn Terraform. 
I am currently Chapter 3, sub section: shared storage for state files.
I have entered the terrafrorm codes to create s3 bucket, dynamodb and to initialise remote backend but i keep getting errors. 
please help me 
this is my code 

```
provider "aws" {
  region = "eu-west-1"
}
resource "aws_s3_bucket" "terraform_state" {
  bucket = "test-2020-bucket"

  lifecycle {
    prevent_destroy = true
  }


  versioning {
    enabled = true
  }

  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
    }
  }
}

resource "aws_dynamodb_table" "locks-2020" {
  name         = "test-2020"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "LockID"

  attribute {
    name = "LockID"
    type = "S"
  }

  tags = {
    Name = "dynamodb-table-1"
    Environment = "development"
  }
}

terraform {
  backend "s3" {
    bucket         = "terraform-test-"
    key            = "global/s3/terraform.tfstate"
    region         = "eu-west-1"
    dynamodb_table = "terraform-test"
    encrypt        = true
  }

}
```
![Screenshot 2019-12-27 at 22 17 57](https://user-images.githubusercontent.com/57905849/71535027-dd6c0380-28fa-11ea-97cb-9835a87b0eed.png)

**Comment by davidATsains** [comment]
i . fixed it

**Comment by brikis98** [comment]
For those that hit this later, you need to create the S3 bucket and DynamoDB table first, and only after they have been created, should you add the `terraform { backend "s3" { ... } }` portion of the code.
