### ISSUE TITLE
metadat in terraform

### ISSUE THREAD

**Issue by payamzowghi** [brikis98/terraform-up-and-running-code#6]
Hi,

Is it possible to edit a bootstrap file in terraform?(like cloudformation)
I'd like to add endpoint of RDS to my wordpress_bootstrap bash file when my instance comes up.

**Comment by brikis98** [comment]
What do you mean by "bootstrap file"? If you mean a [User Data](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html#user-data-shell-scripts) script that runs when an EC2 Instance is booting, then yes. See the [user_data parameter](https://www.terraform.io/docs/providers/aws/r/instance.html#user_data). There are plenty of examples of it being used in this repo.

**Comment by payamzowghi** [comment]
yes, I mean user data. I want to edit my user data when my instance comes up. I'd like to run WordPress service with my bash file. can I add some outputs of my terraform configuration to my bash file?(for instance endpoint of RDS). I'd like to run my terraform file just once. automatically, my bash file can use outputs of resources.

**Comment by brikis98** [comment]
Yes, you can. As I said, there are plenty of examples in this repo ([here's one](https://github.com/brikis98/terraform-up-and-running-code/blob/master/code/terraform/02-intro-to-terraform-syntax/webserver-cluster/main.tf#L14-L18)) and the book.

**Comment by payamzowghi** [comment]
thank you so much.

**Comment by brikis98** [comment]
You bet!
