### ISSUE TITLE
Chapter 7 - dep add step doesn't appear to work. 

### ISSUE THREAD

**Issue by gabrielmccoll** [brikis98/terraform-up-and-running-code#63]
dep ensure -add github.com/gruntwork-io/terratest/modules/terraform@v0.15.9

results in the pictured errors so I'm stuck quite early.
Not sure if I'm being dumb and missing a step. 

Also I don't know Go at all,  should I just skip the whole terratest thing or is there a "Enough Go to use Terratest" thing I can do ?
thank you !  

![image](https://user-images.githubusercontent.com/25871665/96337533-df68a400-107f-11eb-9843-5a42a7be44dc.png)

![image](https://user-images.githubusercontent.com/25871665/96337655-851c1300-1080-11eb-848f-63d2285e752a.png)

**Comment by brikis98** [comment]
Did you follow the exact steps in the book?

<img width="582" alt="Screen Shot 2020-10-18 at 11 15 56 AM" src="https://user-images.githubusercontent.com/711908/96364627-51e68c00-1133-11eb-8662-d1908fec331a.png">

<img width="618" alt="Screen Shot 2020-10-18 at 11 16 19 AM" src="https://user-images.githubusercontent.com/711908/96364635-5d39b780-1133-11eb-9377-4b625133176f.png">

**Comment by gabrielmccoll** [comment]
I think so ! I'll revisit in case I didn't but I rechecked it after issues. Am usually decent at following steps. 

But I guess the separate question of how much Go I need to understand applies. Like if I get this working will I still struggle ?

**Comment by gabrielmccoll** [comment]
okay this time it hung for ages and then seemed to do the thing   

Not sure why it's saying that message RE importing in the project though. seems ok 

![image](https://user-images.githubusercontent.com/25871665/96368112-eeb42400-1149-11eb-85fd-54b6410b3631.png)
