### ISSUE TITLE
[Errata] TU&R 2ed Chapter 2 Page 63 "A Note on Default Virtual Private Clouds.."

### ISSUE THREAD

**Issue by simonderekhughes** [brikis98/terraform-up-and-running-code#64]
TU&R 2ed Chapter 2 Page 63 says "see A Note on Default Virtual Private Clouds for more background information". Where is said information?

**Comment by brikis98** [comment]
What format are you reading the book in? PDF? ePub? Paperback? And where did you get it?

In PDF format, that should be a clickable / tappable link:

<img width="587" alt="Screen Shot 2020-10-20 at 10 08 56 AM" src="https://user-images.githubusercontent.com/711908/96565469-4c687d80-12bc-11eb-8190-5b8f5af8308d.png">

And that link should take you right to the proper section:

<img width="550" alt="Screen Shot 2020-10-20 at 10 08 47 AM" src="https://user-images.githubusercontent.com/711908/96565497-55594f00-12bc-11eb-894e-6d4244dc3a82.png">

**Comment by simonderekhughes** [comment]
This is in the paperback print edition. 
> And where did you get it?
> 
From my local trusty bookseller Heffers in Cambridge, at about £15 more than Amazon.

Can I get a pdf?

S

**Comment by brikis98** [comment]
> This is in the paperback print edition.

Huh, in paperback, I though those links would be replaced with the same text and the page number to go look at? Do you not get any page number there?

**Comment by simonderekhughes** [comment]
>>Huh, in paperback, I though those links would be replaced with the same text and the page number to go look at? Do you not get any page number there?

Nope.

![image](https://user-images.githubusercontent.com/53055061/96702993-3aeda700-138a-11eb-817b-375b00d3d816.png)

**Comment by brikis98** [comment]
That image is too small/blurry to see, but I'll take your word for it. That's a real bummer. I'll check with O'Reilly, the publisher, to figure out what the issue is, as there are quite a few cross-links like this that _should_ unroll into page number references in the print version.

**Comment by simonderekhughes** [comment]
Hi

Ok, thanks for the update.

I guess there are possibly a number of notes missing. Please can I get a
pdf, perhaps from the publisher? I can provide my till receipt if needed.

BTW the  translated samples for GCP no longer work for tf 0.12.26.

Regards
S

**Comment by brikis98** [comment]
OK, sounds like that issue only happened in a couple places in the book, and we're working on fixing it for future re-prints.

Please email me your receipt (jim at ybrikman dot com) for a PDF copy!

**Comment by simonderekhughes** [comment]
Hi

As requested, please find attached the purchase receipt for your book 2nd
Ed.. Please could I have a pdf as reported on github?

Thanks
SImon


[image: IMG_1787.jpeg]

**Comment by brikis98** [comment]
Please email me!
