### ISSUE TITLE
Support for 0.14 and was >3

### ISSUE THREAD

**Issue by christo-ph** [brikis98/terraform-up-and-running-code#67]
Hi,

I am looking for working examples of the current versions of terraform and AWS Provider. When trying to apply the code I am getting (Deploying a Load Balancer from chapter 2)  errors:

```

Error: Error creating Auto Scaling Group: ValidationError: The subnet ID 'vpc-XXXXX' does not exist
        status code: 400, request id: 87fa912f-1465-4066-83a8-41cd7d7397ba

  on main.tf line 32, in resource "aws_autoscaling_group" "example":
  32: resource "aws_autoscaling_group" "example" {
```

**Comment by christo-ph** [comment]
The error was due to an wrong variable (that was mean):

```
resource "aws_autoscaling_group" "example" {
  launch_configuration = aws_launch_configuration.example.name
  vpc_zone_identifier  = data.aws_subnet_ids.default.ids
```

I had wrongly used (missing s):
`vpc_zone_identifier  = data.aws_subnet_ids.default.id`

**Comment by brikis98** [comment]
Ah, yup, that'll do it. Thx for including the resolution!
