### ISSUE TITLE
user_data

### ISSUE THREAD

**Issue by payamzowghi** [brikis98/terraform-up-and-running-code#7]
I generate new bash script and put this line in my bash:
declare instance_address = $(curl http://169.254.169.254/latest/meta-data/public-hostname)

after (terraform plan)I got this error:
Error refreshing state: 1 error(s) occurred:

* data.template_file.user_data: failed to render : 49:86: unknown variable accessed: instance_address

what is the problem?

**Comment by brikis98** [comment]
Did you inline that code within a Terraform file (`.tf`)? If so, you need to escape the dollar sign, or it gets interpreted as [Terraform interpolation](https://www.terraform.io/docs/configuration/interpolation.html). To escape it, use a double dollar sign (`$$`):

```
declare instance_address = $$(curl http://169.254.169.254/latest/meta-data/public-hostname)
```

**Comment by payamzowghi** [comment]
no, I use in my User Data bash script(bootstrap WordPress), not my terraform file.in my bash script, I need the public DNS of my instance.I ran ASG and Launch resources to create a cluster.unfortunately, I couldn't find any attributes relevant to the public DNS in ASG and Launch resources.that's why I want to use hostname metadata.
1-this is my template file:
data "template_file" "user_data" {
  template = "${file("files/wordpress_ubuntu.sh")}"

  vars {
  db_address   = "${aws_db_instance.wordpress-db.address}"
  db_port      = "${aws_db_instance.wordpress-db.port}"
  db_user      = "${aws_db_instance.wordpress-db.username}" 
  db_password  = "${aws_db_instance.wordpress-db.password}" 
 }
}
2-part of my bash file(wordpress_ubuntu.sh) as bootstrap
 declare database_address  = ${db_address}
 declare database_port     = ${db_port}
 declare database_user     = ${db_user}
 declare database_password = ${db_password}
   
  sudo wget http://s3.amazonaws.com/ec2metadata/ec2-metadata
  sudo chmod u+x ec2-metadata                                                 
  sudo cp ec2-metadata /usr/bin/
  declare instance_address = $(curl http://169.254.169.254/latest/meta-data/pu
   
 #update your system
 sudo apt-get update && sudo apt-get upgrade -y

**Comment by brikis98** [comment]
Hm, I'm not sure what that is. Try SSHing to the instance and running your script manually. Perhaps that'll make it clearer what's going on.

**Comment by brikis98** [comment]
No response in ~3 years. Closing.
