### ISSUE TITLE
Ed. 2, Ch. 4 - Terraform modules. Remote state location for webserver uses key for mysql

### ISSUE THREAD

**Issue by ncthanh2000** [brikis98/terraform-up-and-running-code#78]
The file is `stage/services/webserver-cluster/main.tf`

```terraform
module "webserver_cluster" {
  source = "../../../modules/services/webserver-cluster"
  cluster_name = "webservers-stage"
  db_remote_state_bucket = "(YOUR_BUCKET_NAME)"
  db_remote_state_key = "stage/data-stores/mysql/"
}
```
Should `remote_state_key` have been `stage/services/webserver-cluster/terraform.tfstate` instead?

**Comment by brikis98** [comment]
Note that the parameter is called `db_remote_state_key`, so this is the key _for the database_. The `webserver-cluster` module uses a `terraform_remote_state` data source to look up the state at this key and reads outputs from it (e.g., the DB address and port). So I believe pointing it at the mysql key is correct.
