### ISSUE TITLE
chapter 03/04 data.terraform_remote_state.db

### ISSUE THREAD

**Issue by cinek2000** [brikis98/terraform-up-and-running-code#8]
Using the code from chapter 03 and 04 I keep getting the following error:

data.terraform_remote_state.db: Refreshing state...
data.aws_availability_zones.all: Refreshing state...
Error running plan: 1 error(s) occurred:

* data.template_file.user_data: 1 error(s) occurred:

* data.template_file.user_data: Resource 'data.terraform_remote_state.db' does not have attribute 'address' for variable 'data.terraform_remote_state.db.address'

**Comment by brikis98** [comment]
Did you deploy a database and configure it to store remote state in S3?

**Comment by cinek2000** [comment]
ah that'd explain it, thanks!
