### ISSUE TITLE
configure HTTPS in ELB 

### ISSUE THREAD

**Issue by payamzowghi** [brikis98/terraform-up-and-running-code#9]
if I want to use HTTPS(port 443) as a listener in my loadbalancer, I have to change my apache's configuration in back-end(web server)?or I left it same as HTTP. I mean besides network configuration.

**Comment by brikis98** [comment]
You can have the ELB listen on HTTPS but send the traffic to the HTTP port of your back-end server, so no configuration change is necessary. However, to use HTTPS, you'll need a TLS certificate.

**Comment by payamzowghi** [comment]
do you know how do I configure my apache2 to force ELB redirect http to https.
this is my configuration but it dosen't work
``
<VirtualHost *:80>
RewriteEngine On
RewriteCond %{HTTP:X-Forwarded-Proto} http
RewriteRule https://%{ec2-54-218-254-255.us-west-2.compute.amazonaws.com}%{REQUEST_URI} [R=301,L]
</VirtualHost>

``

**Comment by brikis98** [comment]
You don't force the ELB to redirect. You force the user's web browser to redirect. Therefore, the `RewriteRule` should not point at your own EC2 Instance, but at the ELB or whatever domain name you're using.

**Comment by payamzowghi** [comment]
1-how do I force the user's web browser to redirect?
2-how do I use RewriteRule at the ELB?

**Comment by brikis98** [comment]
These are all questions you can answer with a Google search!

1. Return a 301 or 302 redirect.
1. You do the RewriteRule in your web server as you're doing now. The ELB has nothing to do with this.

**Comment by payamzowghi** [comment]
Thank you.

**Comment by brikis98** [comment]
Issue was resolved 3 years ago. Closing.
